# Generated by Django 5.0 on 2023-12-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEspecialidad', models.TextField()),
                ('estadoEspecialidad', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('digito', models.CharField(max_length=1)),
                ('primernombre', models.CharField(max_length=50)),
                ('primerapellido', models.CharField(max_length=50)),
                ('segundonombre', models.CharField(max_length=50)),
                ('segundoapellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('imagen', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaciente', models.IntegerField()),
                ('nroCJPPU', models.CharField(max_length=12)),
                ('fechaVencimientoAYEX', models.DateField()),
                ('esBPS', models.CharField(max_length=1)),
                ('deuda', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='TutorPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.persona')),
                ('pacientes', models.ManyToManyField(to='ccapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('nroTecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nroCJPPU', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.persona')),
                ('especialidades', models.ManyToManyField(to='ccapp.especialidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroFuncionario', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.usuario')),
            ],
        ),
    ]
