# Generated by Django 5.0 on 2024-01-04 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEspecialidad', models.TextField()),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('idInstitucionEducativa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreInstitucionEducativa', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nroCJPPU', models.CharField(max_length=12)),
                ('fechaVencimientoAYEX', models.DateField()),
                ('esBPS', models.CharField(max_length=1)),
                ('deuda', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('idInstitucionEducativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.institucioneducativa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateTimeField()),
                ('total', models.FloatField()),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('digito', models.CharField(max_length=1)),
                ('primernombre', models.CharField(max_length=50)),
                ('primerapellido', models.CharField(max_length=50)),
                ('segundonombre', models.CharField(max_length=50)),
                ('segundoapellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('imagen', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.persona'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nroFuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FuncionarioAuthor', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FuncionarioUsuario', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('idPrestador', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePrestador', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('idSesion', models.AutoField(primary_key=True, serialize=False)),
                ('diaSemana', models.IntegerField()),
                ('horaInicio', models.DateTimeField()),
                ('horaFin', models.DateTimeField()),
                ('cantidadPacientes', models.IntegerField()),
                ('agrupacion', models.IntegerField()),
                ('unicavez', models.BooleanField()),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('idEspecialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('horaFin', models.DateTimeField()),
                ('diaSemana', models.IntegerField()),
                ('horaConsulta', models.DateTimeField()),
                ('estado', models.IntegerField()),
                ('cantidadConsultas', models.IntegerField()),
                ('cantidadConsultasRestantes', models.IntegerField()),
                ('observaciones', models.CharField(max_length=250)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.paciente')),
                ('idPrestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.prestador')),
                ('idSesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('nroTecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nroCJPPU', models.CharField(max_length=12)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('especialidades', models.ManyToManyField(to='ccapp.especialidad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sesion',
            name='nroTecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.tecnico'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('hora', models.DateTimeField()),
                ('asisteAfiliado', models.BooleanField()),
                ('asisteTecnico', models.BooleanField()),
                ('estado', models.IntegerField()),
                ('observaciones', models.CharField(max_length=250)),
                ('fechaGeneracion', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('idEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.evaluacion')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.paciente')),
                ('idSesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.sesion')),
                ('nroTecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('idTratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(max_length=250)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.paciente')),
                ('idPrestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.prestador')),
                ('idSesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroConsulta',
            fields=[
                ('idRegistroConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('hora', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=250)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('idConsulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.consulta')),
                ('idEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.evaluacion')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.paciente')),
                ('nroTecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.tecnico')),
                ('idTratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='idTratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccapp.tratamiento'),
        ),
        migrations.CreateModel(
            name='TutorPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pacientes', models.ManyToManyField(to='ccapp.paciente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.persona')),
            ],
        ),
    ]
