# Generated by Django 5.0 on 2023-12-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especalidad',
            fields=[
                ('idEspecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEspecialidad', models.TextField()),
                ('fechacreado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
