# Generated by Django 5.0 on 2023-12-11 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Persona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Persona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='tecnico',
            old_name='Persona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='tutorpaciente',
            old_name='Persona',
            new_name='persona',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
