# Generated by Django 5.0 on 2023-12-26 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0002_remove_especialidad_estadoespecialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cantidadConsultas',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cantidadConsultasRestantes',
        ),
        migrations.AddField(
            model_name='pago',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccapp.paciente'),
            preserve_default=False,
        ),
    ]
