# Generated by Django 5.0 on 2023-12-28 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0003_remove_consulta_cantidadconsultas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('idInstitucionEducativa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreInstitucionEducativa', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sesion',
            name='idEspecialidad',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='ccapp.especialidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='idInstitucionEducativa',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='ccapp.institucioneducativa'),
            preserve_default=False,
        ),
    ]
